// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSbl-RlfidVBlo2i1_jTuCtqo8lgTTbGg',
    appId: '1:60275310305:web:YOUR_WEB_APP_ID',
    messagingSenderId: '60275310305',
    projectId: 'calldetector-5d61e',
    authDomain: 'calldetector-5d61e.firebaseapp.com',
    storageBucket: 'calldetector-5d61e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSbl-RlfidVBlo2i1_jTuCtqo8lgTTbGg',
    appId: '1:60275310305:android:7c8f0e3b4d5a6e9f9ac1a0',
    messagingSenderId: '60275310305',
    projectId: 'calldetector-5d61e',
    storageBucket: 'calldetector-5d61e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSbl-RlfidVBlo2i1_jTuCtqo8lgTTbGg',
    appId: '1:60275310305:ios:9d7e8f2a3c4b5d6e9ac1a0',
    messagingSenderId: '60275310305',
    projectId: 'calldetector-5d61e',
    storageBucket: 'calldetector-5d61e.firebasestorage.app',
    iosBundleId: 'com.designated.driverapp',
  );
}
